### ISSUE TITLE
a idea

### ISSUE THREAD

**Issue by Marshtomp21** [Mateget/RemoveShinyCharm#1]
please add dynamaxband,ovelcharm,megaring's remove command!

**Comment by Mateget** [comment]
Hi, do you think the ovelcharm should be placed in the inventory or deleted ?

I will look about your idea this week-end

**Comment by Marshtomp21** [comment]
> Hi, do you think the ovelcharm should be placed in the inventory or deleted ?
> 
> I will look about your idea this week-end
I think both are ok. Thank you for your reply, you are a good developer
